# favicons
icons: true

# how links show: you have 2 choice--text or icon.
links_text_enable: false
links_icon_enable: true

# posts
post: 
  show_updated: false
  ## Post_meta
  meta_enable: true

  author_enable: true
  date_enable: true
  category_enable: true
  ## Post copyright
  copyright_enable: true

  copyright_author_enable: false
  copyright_permalink_enable: true
  copyright_license_enable: false
  copyright_license_text: copyright (c) 2022 neverbot
  copyright_slogan_enable: false

archive:
  sort_updated: false
  show_all_posts: false
  post_per_page: 10
  post_per_page_in_list: 20

## toc
toc:
  post_enable: true
  page_enable: true

# pages
page:
  page_title_enable: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
# date_format: MMMM D, YYYY
date_format: dddd D [de] MMMM [de] YYYY
time_format: HH:mm:ss

# stylesheets loaded in the <head>
stylesheets:
  - /css/style.css

# scripts loaded in the end of the body
scripts:
  - /js/script.js
  - /js/tocbot.min.js
    # tscanlin/tocbot: Build a table of contents from headings in an HTML document.
    # https://github.com/tscanlin/tocbot
