# general build configuration
[build]
  base = "web/"
  publish = "web/public"
  command = "npm run build:pro"

# redirect from blog.neverbot.com
[[redirects]]
  from = "https://blog.neverbot.com/*"
  to = "https://neverbot.com/:splat"
  status = 301
  force = true

# redirect from www.neverbot.com
[[redirects]]
  from = "https://www.neverbot.com/*"
  to = "https://neverbot.com/:splat"
  status = 301
  force = true
